services:
  postgres:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      TZ: America/Campo_Grande
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql
    mem_limit: 200m
    mem_reservation: 100m

  springboot:
    build: ./Backend
    ports:
      - "8080:8080"
    environment:
      TZ: America/Campo_Grande
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      REFRESH_EXPIRATION: ${REFRESH_EXPIRATION}
      PEPPER: ${PEPPER}
      WPP_URL: ${WPP_URL}
      WPP_SESSION: ${WPP_SESSION}
      WPP_TOKEN: ${WPP_TOKEN}
      SCRAPER_URL: ${SCRAPER_URL}
      WPP_NUMERO: ${WPP_NUMERO}
      RESEND_TOKEN: ${RESEND_TOKEN}
      URL_FRONTEND: ${URL_FRONTEND}
    depends_on:
      - postgres
      - scraper
      - wppconnect
    mem_limit: 600m
    mem_reservation: 450m

  scraper:
    build: ./worker
    ports:
      - "8000:8000"
    mem_limit: 200m
    mem_reservation: 80m

  wppconnect:
    build:
      context: ./wppconnect-server
    volumes:
      - ./wppconnect-server/dist/config.js:/usr/src/wpp-server/dist/config.js
      - ./wppconnect-server/tokens:/usr/src/wpp-server/tokens
      - ./wppconnect-server/userDataDir:/usr/src/wpp-server/userDataDir
    ports:
      - "21465:21465"
    mem_limit: 700m
    mem_reservation: 550m

volumes:
  postgres_data:
  wpp_tokens: